### ISSUE TITLE
Spatial Control

### ISSUE THREAD

**Issue by InstantWindy** [naoto0804/pytorch-AdaIN#12]
I'm sorry to trouble you ,I implement the Spatial Control by pytorch.but I have some question.
I think the contentFeatureBG dimension and targetFeature dimension are different from contentFeature dimension,but the code writes: targetFeature = targetFeature:viewAs(contentFeature),I don't know

![tim 20180519154009](https://user-images.githubusercontent.com/23608180/40270372-ccb787f4-5bbe-11e8-8aae-cb386ae0cbb2.png)
the following is my pytorch code:
   if mask_path!=None:
       _,C,H,W=content_f.size()
       mask_img=Image.open(mask_path).resize((W,H))
      mask=content_tf(mask_img) #W,H
      maskView=mask.view(-1) #H*W
      idx=np.where(maskView.numpy()==0）#0->H*W
      bgmask=torch.LongTensor(torch.from_numpy(idx[0]))#0->H*W
                 
      contenF=content_f.view(C,-1)  #C,H*W
      contentFBG=contentF[:,bgmask].view(C,bgmask.size(0),1)
      target_bg=adaptive_instance_normalization(contentFBG, style_f).squeeze()

      feat=Variable（torch.FloatTensor(C,H*W).zero_().cuda(),volatile=True)
      feat=target_bg[:,bgmask]
      feat=feat.expand(content_f.size())

**Comment by crcrpar** [comment]
Hi, @InstantWindy
I think the screenshot is not from this repository, because the code in the screenshot seems to be Torch7 code.

Also, the variables with red line have the same size, I'm not sure though.
