### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rgeirhos** [naoto0804/pytorch-AdaIN#16]
Thanks for this implementation, very cool!
I'm using it for my research, and I was wondering whether you could indicate which license applies to the repo?

I would like to make my code openly available on github, and since it is based on your implementation, I would obviously give you credit in the README but I'm not sure whether any license (e.g. MIT) applies to your code.

**Comment by rgeirhos** [comment]
Awesome, thanks for the fast response!
That's great, I will release my code under the MIT license as well (gives others clarity about what they can use it for).

**Comment by naoto0804** [comment]
Thanks. Please let me know when you release your codes (just from curiosity)

**Comment by rgeirhos** [comment]
Sure thing ;)

**Comment by naoto0804** [comment]
@rgeirhos Cool work! https://github.com/rgeirhos/Stylized-ImageNet

**Comment by naoto0804** [comment]
I saw it on twitter;) Hope your submission to ICLR2019 is accepted!!

**Comment by rgeirhos** [comment]
Interesting indeed!
