### ISSUE TITLE
After training  the .tar file is unpackable

### ISSUE THREAD

**Issue by ferric123** [naoto0804/pytorch-AdaIN#18]
I trained on my own dataset to get the decoder, however, I got this error when I attempted to unpack the trained decoder with the command  tar -xvzf decoder_iter_160000.pth.tar:
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by naoto0804** [comment]
You don't have to decompress it. You might just do `model.load_state_dict(torch.load(foo.pth.tar))` or something like that to load the model. (Please refer to `test.py`)
