### ISSUE TITLE
convert torch to pytorch

### ISSUE THREAD

**Issue by omar-arab-oghli** [naoto0804/pytorch-AdaIN#20]
running the commands:

`python torch_to_pytorch.py --model models/vgg_normalised.t7`
`python torch_to_pytorch.py --model models/decoder.t7`

produces the following error: 
`Traceback (most recent call last):
  File "torch_to_pytorch.py", line 9, in <module>
    from torch.utils.serialization import load_lua
ModuleNotFoundError: No module named 'torch.utils.serialization'`

Please refer to this issue: https://github.com/pytorch/pytorch/issues/14630

**Comment by Hvitgar** [comment]
This happens when you try to convert the models with a recent pyTorch version. For conversion (and only for conversion), pyTorch 0.4 is needed since `torch-to-pytorch.py` uses legacy code that has been removed past version 0.4.

**Comment by naoto0804** [comment]
@Hvitgar Thank you for pointing out!

**Comment by ArturoDeza** [comment]
Reviving this thread. Is it possible for someone to provide a link for the converted model?

**Comment by naoto0804** [comment]
I dit it. See #21.
