### ISSUE TITLE
Why add a 3*3*1*1 conv layer on top of official vgg-19 structure?

### ISSUE THREAD

**Issue by CharlesNord** [naoto0804/pytorch-AdaIN#22]
Hi, I found that different from official vgg-19, in this project you added a conv layer of `3*3*1*1` to the input of vgg-19. Could you please tell me the reason? Besides, how did you train this new version of vgg-19 and get the pretrained feature extractor?

**Comment by naoto0804** [comment]
I adapt everything from the [original implememtation](https://github.com/xunhuang1995/AdaIN-style), so I hope it should be the same..

**Comment by diaodeyi** [comment]
> Hi, I found that different from official vgg-19, in this project you added a conv layer of `3*3*1*1` to the input of vgg-19. Could you please tell me the reason? Besides, how did you train this new version of vgg-19 and get the pretrained feature extractor?

Did you find out ?
