### ISSUE TITLE
what does the function of coral mean？

### ISSUE THREAD

**Issue by xuzhongyou** [naoto0804/pytorch-AdaIN#24]
Thanks for your job, it helps me a lot. I have no idea about the function of coral in function.py ?
![image](https://user-images.githubusercontent.com/16487416/63944149-9a606780-caa3-11e9-8e8d-9c44039c63be.png)

**Comment by naoto0804** [comment]
It tries to re-implment [this section](https://github.com/xunhuang1995/AdaIN-style/tree/6d8ac287f35010faf8feece4047bfe86c8c007d0#transfer-style-but-not-color)
See [here](https://github.com/xunhuang1995/AdaIN-style/blob/6d8ac287f35010faf8feece4047bfe86c8c007d0/lib/utils.lua#L57-L78) for the original implementation in torch.
