### ISSUE TITLE
No module named 'torch.utils.serialization'

### ISSUE THREAD

**Issue by KokeCacao** [naoto0804/pytorch-AdaIN#25]
```
python torch_to_pytorch.py --model models/vgg_normalised.t7
Traceback (most recent call last):
  File "torch_to_pytorch.py", line 9, in <module>
    from torch.utils.serialization import load_lua
ModuleNotFoundError: No module named 'torch.utils.serialization'
```
It seems like the function is long removed by pytorch: https://stackoverflow.com/questions/54107156/modulenotfounderror-no-module-named-torch-utils-serialization

We should use https://github.com/bshillingford/python-torchfile instead.

**Comment by naoto0804** [comment]
Thanks for the suggestion! 
Since I don't have enough time to work on this, PR is welcome;(

**Comment by naoto0804** [comment]
Thank you for the suggestion! I'm now thinking of dropping support for converting torch to pytorch since it's very old. 
If you want to get the converted weight, please refer to #21

**Comment by naoto0804** [comment]
I have updated the code to work on v1.2 #26. 
I also share the converted version of the models (see [here](https://github.com/naoto0804/pytorch-AdaIN#download-models)).
