### ISSUE TITLE
 vgg_normalized.pth/decoder.pth brocken

### ISSUE THREAD

**Issue by Jeshofm** [naoto0804/pytorch-AdaIN#34]
The link for the model downloads is broken. 
 vgg_normalized.pth/decoder.pth 
Can someone help?

**Comment by whq-hqw** [comment]
Same problem here

**Comment by naoto0804** [comment]
Could you check it again?

**Comment by naoto0804** [comment]
Please put 👍 if anyone can access.

**Comment by Jeshofm** [comment]
It works. Thanks a lot
