### ISSUE TITLE
pre-trained vgg encoder

### ISSUE THREAD

**Issue by hongsukchoi** [naoto0804/pytorch-AdaIN#35]
Hi thanks for your great effort.

I am curious where the weight of the pre-trained vgg encoder are from. I trained the whole model with your pre-traiend vgg encoder, and the style-transfered result seems to have some portrait effect even the train set (both style source and content source) is not composed of portraits.

So I am suspicious that the pre-trained vgg encoder weight is trained on portraits such as WikiArt.
Could you clarify about the vgg encoder pre-training? 

Thank you

**Comment by naoto0804** [comment]
During training, the VGG encoder is not trained during training (see [here](https://github.com/naoto0804/pytorch-AdaIN/blob/master/train.py#L112)). Only the decoder is trained.

**Comment by hongsukchoi** [comment]
Hi, indeed I checked the codes. Also I checked other AdaIN results, and I think the portrait-like artifact (ex. rugged background) is inherent in AdaIN as you said.
Thank you~
