### ISSUE TITLE
Using vgg_normalised.pth on Windows platform

### ISSUE THREAD

**Issue by yuxijin** [naoto0804/pytorch-AdaIN#41]
Hello, there. ^_^ I am trying to perform your code on my laptop which is equipped with the Windows 10 operating system. However, it cannot successfully load the pre-trained model "vgg_normalised.pth". I guess it is probably because that your pre-trained model is obtained under Linux. Could you please provide a version that can be used under Windows 10 or give me some instruction on how to train the "vgg_normalise.pth" under Windows?

**Comment by naoto0804** [comment]
Hi, could you show me the logs raised during the execution?

**Comment by naoto0804** [comment]
Please re-open the issue if you have anything to discuss!
